* English/French variable name concordance ;
* input dataset will be overwritten ;
%macro EnglishFrenchRenames(DS);
%local RenameDS TempDS NewDSNames Renames;
%let NewDSNames = %GetNewDSNames(NumNames = 3);
%let RenameDS = %scan(&NewDSNames, 1);
%let TempDS = %scan(&NewDSNames, 2);
%let TempDS2 = %scan(&NewDSNames, 3);

data &RenameDS;
length Eng Fre $20.;
Eng = "NGD_UID"; Fre = "BNDGIDU"; output;
Eng = "NGD_UID"; Fre = "BNDG_IDU"; output;
Eng = "NAME"; Fre = "NOM"; output;
Eng = "TYPE"; Fre = "GENRE"; output;
Eng = "DIR"; Fre = "DIR"; output;
Eng = "AFL_VAL"; Fre = "ADG_VAL"; output;
Eng = "ATL_VAL"; Fre = "AAG_VAL"; output;
Eng = "AFR_VAL"; Fre = "ADD_VAL"; output;
Eng = "ATR_VAL"; Fre = "AAD_VAL"; output;
Eng = "CSDUID_L"; Fre = "SDRIDU_G"; output;
Eng = "CSDNAME_L"; Fre = "SDRNOM_G"; output;
Eng = "CSDTYPE_L"; Fre = "SDRGENRE_G"; output;
Eng = "CSDUID_R"; Fre = "SDRIDU_D"; output;
Eng = "CSDNAME_R"; Fre = "SDRNOM_D"; output;
Eng = "CSDTYPE_R"; Fre = "SDRGENRE_D"; output;
Eng = "CMAUID_L"; Fre = "RMRIDU_G"; output;
Eng = "CMANAME_L"; Fre = "RMRNOM_G"; output;
Eng = "CMATYPE_L"; Fre = "RMRGENRE_G"; output;
Eng = "CMAUID_R"; Fre = "RMRIDU_D"; output;
Eng = "CMANAME_R"; Fre = "RMRNOM_D"; output;
Eng = "CMATYPE_R"; Fre = "RMRGENRE_D"; output;
Eng = "PRUID_L"; Fre = "PRIDU_G"; output;
Eng = "PRNAME_L"; Fre = "PRNOM_G"; output;
Eng = "PRUID_R"; Fre = "PRIDU_D"; output;
Eng = "PRNAME_R"; Fre = "PRNOM_D"; output;
Eng = "RANK"; Fre = "RANG"; output;
Eng = "CLASS"; Fre = "CLASS"; output;
Eng = "DBRPLAMX"; Fre = "IDPRLAMX"; output;
Eng = "DBRPLAMY"; Fre = "IDPRLAMY"; output;
Eng = "CARUID"; Fre = "RARIDU"; output;
Eng = "CARENAME"; Fre = "RARANOM"; output;
Eng = "CARFNAME"; Fre = "RARFNOM"; output;
Eng = "ADAUID"; Fre = "ADAIDU"; output;
Eng = "PRUID"; Fre = "PRIDU"; output;
Eng = "PRNAME"; Fre = "PRNOM"; output;
Eng = "PRENAME"; Fre = "PRANOM"; output;
Eng = "PRFNAME"; Fre = "PRFNOM"; output;
Eng = "PREABBR"; Fre = "PRAABREV"; output;
Eng = "PRFABBR"; Fre = "PRFABREV"; output;
Eng = "CDUID"; Fre = "DRIDU"; output;
Eng = "CDNAME"; Fre = "DRNOM"; output;
Eng = "CDTYPE"; Fre = "DRGENRE"; output;
Eng = "ERUID"; Fre = "R_IDU"; output;
Eng = "ERNAME"; Fre = "R_NOM"; output;
Eng = "ERUID"; Fre = "RÉIDU"; output;
Eng = "ERNAME"; Fre = "RÉNOM"; output;
Eng = "CCSUID"; Fre = "SRUIDU"; output;
Eng = "CCSNAME"; Fre = "SRUNOM"; output;
Eng = "CSDUID"; Fre = "SDRIDU"; output;
Eng = "CSDNAME"; Fre = "SDRNOM"; output;
Eng = "CSDTYPE"; Fre = "SDRGENRE"; output;
Eng = "CMAUID"; Fre = "RMRIDU"; output;
Eng = "CMANAME"; Fre = "RMRNOM"; output;
Eng = "CMATYPE"; Fre = "RMRGENRE"; output;
Eng = "CMAPUID"; Fre = "RMRPIDU"; output;
Eng = "SACTYPE"; Fre = "CSSGENRE"; output;
Eng = "SACCODE"; Fre = "CSSCODE"; output;
Eng = "FEDUID"; Fre = "C_FIDU"; output;
Eng = "FEDNAME"; Fre = "C_FNOM"; output;
Eng = "FEDENAME"; Fre = "C_FANOM"; output;
Eng = "FEDFNAME"; Fre = "C_FFNOM"; output;
Eng = "FEDUID"; Fre = "CÉFIDU"; output;
Eng = "FEDNAME"; Fre = "CÉFNOM"; output;
Eng = "FEDENAME"; Fre = "CÉFANOM"; output;
Eng = "FEDFNAME"; Fre = "CÉFFNOM"; output;
Eng = "CTUID"; Fre = "SRIDU"; output;
Eng = "CTNAME"; Fre = "SRNOM"; output;
Eng = "DPLUID"; Fre = "LDIDU"; output;
Eng = "DPLNAME"; Fre = "LDNOM"; output;
Eng = "DPLTYPE"; Fre = "LDGENRE"; output;
Eng = "PCUID"; Fre = "CPIDU"; output;
Eng = "PCNAME"; Fre = "CPNOM"; output;
Eng = "PCTYPE"; Fre = "CPGENRE"; output;
Eng = "PCPUID"; Fre = "CPPIDU"; output;
Eng = "PCCLASS"; Fre = "CPCLASSE"; output;
Eng = "DAUID"; Fre = "ADIDU"; output;
Eng = "DBUID"; Fre = "IDIDU"; output;
Eng = "DBRPLAT"; Fre = "IDPRLAT"; output;
Eng = "DBRPLONG"; Fre = "IDPRLONG"; output;
Eng = "DGUID"; Fre = "IDUGD"; output;
Eng = "DGUIDP"; Fre = "IDUGDP"; output;
Eng = "MRCNAME"; Fre = "MRCNOM"; output;
Eng = "MRCTYPE"; Fre = "MRCGENRE"; output;
Eng = "MRCUID"; Fre = "MRCIDU"; output;
Eng = "LANDAREA"; Fre = "SUPTERRE"; output;
Eng = "CSDDGUID_L"; Fre = "SDRIDUGD_G"; output;
Eng = "CSDDGUID_R"; Fre = "SDRIDUGD_D"; output;
Eng = "PRDGUID_L"; Fre = "PRIDUGD_G"; output;
Eng = "PRDGUID_R"; Fre = "PRIDUGD_D"; output;
Eng = "DTUID"; Fre = "CVIDU"; output;
Eng = "DTNAME"; Fre = "CVNOM"; output;
Eng = "DTTYPE"; Fre = "CVGENRE"; output;
Eng = "ECUMENE"; Fre = "ÉCOUMÈNE"; output;
Eng = "ECUID"; Fre = "ÉCIDU"; output;
Eng = "CLASS"; Fre = "CLASSE"; output;
Eng = "CFSAUID"; Fre = "RTACIDU"; output;
Eng = "HR_UID"; Fre = "RSS_IDU"; output;
Eng = "LHN_UID"; Fre = "RLISS_IDU"; output;
Eng = "ENGNAME"; Fre = "NOMANG"; output;
Eng = "FRENAME"; Fre = "NOMFRA"; output;
run;
data &RenameDS;
set &RenameDS;
Eng = upcase(Eng); Fre = upcase(Fre);
run;


%let renames = ;
proc contents data = &DS noprint out = &TempDS; run;
proc sql noprint;
create table &TempDS2 as
  select trim(Fre) || " = " || trim(Eng) as Command
    from &TempDS, &RenameDS
    where upcase(&TempDS..name) = upcase(&RenameDS..Fre);
select Command into :Renames separated by " " from &TempDS2;
quit;
run;
proc delete data = &RenameDS &TempDS &TempDS2; run;
data &DS;
set &DS(rename = (&Renames));
run;
%mend;
